# Generated by Django 4.2.2 on 2023-06-06 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='arvoreDetalhe',
            fields=[
                ('nome', models.CharField(max_length=10)),
                ('cod_planta', models.AutoField(primary_key=True, serialize=False)),
                ('data_cadastro', models.DateField()),
                ('observaçao', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='controleEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('contato', models.CharField(max_length=12)),
                ('endereco', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=10)),
                ('data_adicao', models.DateTimeField()),
                ('data_plantio', models.DateField()),
                ('qtdPlanta', models.IntegerField()),
                ('local_plantio', models.CharField(max_length=15)),
                ('codRegistro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.arvoredetalhe')),
            ],
        ),
    ]
